project:
  type: book
  output-dir: docs

book:
  title: "Unravelling Superposition"
  author: "R.A. Stringer"
  cover-image: "images/cover_image.png"
  chapters:
    - index.qmd
    - introduction.ipynb
    - superposition.ipynb
    - language_models.ipynb
    - sparse_autoencoders.ipynb
    - for_policy_specialists.ipynb
    - summary.qmd


bibliography: references.bib

format:
  html:
    theme: cyborg
  pdf:
    documentclass: scrreprt
    

